#include <cul/cul_global.h>
#include <cul/cul_string_type.h>

static const uint16_t cul_string_type_ascii_data[256] = {
	/* 0x00 - 0x08 */
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	/* 0x09 - 0x0f */
	CUL_STRING_CNTRL|CUL_STRING_SPACE,
	CUL_STRING_CNTRL|CUL_STRING_SPACE,
	CUL_STRING_CNTRL|CUL_STRING_SPACE,
	CUL_STRING_CNTRL|CUL_STRING_SPACE,
	CUL_STRING_CNTRL|CUL_STRING_SPACE,
	CUL_STRING_CNTRL|CUL_STRING_SPACE,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	/* 0x10 - 0x18 */
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	/* 0x10 - 0x1f */
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	CUL_STRING_CNTRL,
	/* 0x20 - 0x28 */
	CUL_STRING_PRINT|CUL_STRING_SPACE,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	/* 0x29 - 0x2f */
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
	CUL_STRING_GRAPH|CUL_STRING_PRINT|CUL_STRING_PUNCT,
};

const uint16_t *const cul_string_type_ascii = cul_string_type_ascii_data;
